from enum import Enum

class GiaGrade(Enum):
    GIA_EXCELLENT = "GIA_EXCELLENT"
    GIA_VERY_GOOD = "AGS_VERY_GOOD"
    GIA_GOOD = "AGS_GOOD"
    GIA_FAIR = "AGS_FAIR"
    GIA_POOR = "AGS_POOR"

class AgsGrade(Enum):
    AGS_IDEAL = "AGS_IDEAL"
    AGS_EXCELLENT = "AGS_EXCELLENT"
    AGS_VERY_GOOD = "AGS_VERY_GOOD"
    AGS_GOOD = "AGS_GOOD"
    AGS_FAIR = "AGS_FAIR"
    AGS_POOR = "AGS_POOR"
